#!/bin/sh
# We need to know samplerate from pdsettings 
CONFIG_FILE='/home/patch/modulePre/config.json'
pdsettings=$(cat $CONFIG_DIR/config.json | jq '.pdsettings');
samplerate=$(echo $pdsettings | jq -r '.samplerate');

# exec is used to 'morph' the shell interpreter process into jackd process, saving some system resources.
exec /usr/bin/jackd -t 2000 -R -P 95 -d alsa  -r $samplerate -p 64 -n 2 -X seq -s -S 
